"""textual-themes — Retro color themes for Textual TUI apps.

Usage:
    from textual_themes import C64_THEME, AMIGA_THEME
    app.register_theme(C64_THEME)
    app.theme = "c64"
"""
from __future__ import annotations

from .themes import (
    AMIGA_THEME,
    ATARI_ST_THEME,
    BATMAN_THEME,
    BEOS_THEME,
    BLUESY_THEME,
    C64_THEME,
    CLASSIC_NAVY_THEME,
    FREEBSD_THEME,
    GAMEBOY_THEME,
    GOLDFINGER_THEME,
    HULK_THEME,
    IBM_TERMINAL_THEME,
    LINUX_MINT_THEME,
    MACOS_THEME,
    MARTINI_RACING_THEME,
    MIAMI_VICE_THEME,
    MSDOS_THEME,
    NEXTSTEP_THEME,
    OPENSUSE_THEME,
    OS2_WARP_THEME,
    PAN_AM_THEME,
    PLAN9_THEME,
    RASPBERRY_PI_THEME,
    RED_HAT_THEME,
    RETRO_THEME_NAMES,
    RETRO_THEMES,
    SOLARIS_CDE_THEME,
    SPIDERMAN_THEME,
    METROPOLIS_THEME,
    SYNTHWAVE_THEME,
    THEME_DISPLAY_NAMES,
    TUDOR_THEME,
    UBUNTU_THEME,
    WINDOWS_XP_THEME,
    register_all,
)

__version__ = "0.4.0"
__author__ = "Michael Blaess"

__all__ = [
    "C64_THEME",
    "AMIGA_THEME",
    "ATARI_ST_THEME",
    "IBM_TERMINAL_THEME",
    "NEXTSTEP_THEME",
    "BEOS_THEME",
    "UBUNTU_THEME",
    "MACOS_THEME",
    "WINDOWS_XP_THEME",
    "MSDOS_THEME",
    "PLAN9_THEME",
    "SOLARIS_CDE_THEME",
    "OS2_WARP_THEME",
    "OPENSUSE_THEME",
    "LINUX_MINT_THEME",
    "RED_HAT_THEME",
    "RASPBERRY_PI_THEME",
    "FREEBSD_THEME",
    "TUDOR_THEME",
    "BLUESY_THEME",
    "GOLDFINGER_THEME",
    "HULK_THEME",
    "BATMAN_THEME",
    "CLASSIC_NAVY_THEME",
    "GAMEBOY_THEME",
    "PAN_AM_THEME",
    "SYNTHWAVE_THEME",
    "MIAMI_VICE_THEME",
    "MARTINI_RACING_THEME",
    "METROPOLIS_THEME",
    "SPIDERMAN_THEME",
    "RETRO_THEMES",
    "RETRO_THEME_NAMES",
    "THEME_DISPLAY_NAMES",
    "register_all",
]
