"""textual-themes — Retro color themes for Textual TUI apps.

Usage:
    from textual_themes import BROTKASTEN_THEME, BOING_THEME
    app.register_theme(BROTKASTEN_THEME)
    app.theme = "brotkasten"
"""
from __future__ import annotations

from .themes import (
    BEASTIE_THEME,
    BEBOX_THEME,
    BLUESY_THEME,
    BOING_THEME,
    BRICK_THEME,
    BROTKASTEN_THEME,
    BUNTY_THEME,
    CLASSIC_NAVY_THEME,
    CLASSIC_TERMINAL_THEME,
    CLIPPER_THEME,
    COMMANDR_THEME,
    CRIMSON_THEME,
    CUPERTINO_THEME,
    FIFTY_EIGHT_THEME,
    FLUGHUND_THEME,
    GEEKO_THEME,
    GEMSTONE_THEME,
    GOLDFINDER_THEME,
    HULKULA_THEME,
    LUNA_THEME,
    METROPOLIS_THEME,
    MIAMI_THEME,
    MINTY_THEME,
    MOTIF_THEME,
    NEXT_THEME,
    PLAN9_THEME,
    RACING_THEME,
    RAZZY_THEME,
    RETRO_THEME_NAMES,
    RETRO_THEMES,
    SPIDERIZED_THEME,
    SYNTHWAVE_THEME,
    THEME_DISPLAY_NAMES,
    WARP_THEME,
    register_all,
)

__version__ = "0.5.0"
__author__ = "Michael Blaess"

__all__ = [
    "BROTKASTEN_THEME",
    "BOING_THEME",
    "GEMSTONE_THEME",
    "CLASSIC_TERMINAL_THEME",
    "NEXT_THEME",
    "BEBOX_THEME",
    "BUNTY_THEME",
    "CUPERTINO_THEME",
    "LUNA_THEME",
    "COMMANDR_THEME",
    "PLAN9_THEME",
    "MOTIF_THEME",
    "WARP_THEME",
    "GEEKO_THEME",
    "MINTY_THEME",
    "CRIMSON_THEME",
    "RAZZY_THEME",
    "BEASTIE_THEME",
    "FIFTY_EIGHT_THEME",
    "BLUESY_THEME",
    "GOLDFINDER_THEME",
    "HULKULA_THEME",
    "FLUGHUND_THEME",
    "CLASSIC_NAVY_THEME",
    "BRICK_THEME",
    "CLIPPER_THEME",
    "SYNTHWAVE_THEME",
    "MIAMI_THEME",
    "RACING_THEME",
    "METROPOLIS_THEME",
    "SPIDERIZED_THEME",
    "RETRO_THEMES",
    "RETRO_THEME_NAMES",
    "THEME_DISPLAY_NAMES",
    "register_all",
]
